Examen/Models/ErrorViewModel.cs
using System;

namespace Examen.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Examen/Models/Prospecto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Examen.Models
{
    public class Prospecto
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage ="El nombre es obligatorio")]
        [Display(Name ="Nombre")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "El primer apellido es obligatorio")]
        [Display(Name = "Primer apellido")]
        public string apellidoP { get; set; }

        [Display(Name = "Segundo apellido")]
        public string apellidoM { get; set; }

        [Display(Name = "Calle")]
        [Required(ErrorMessage = "La calle es obligatoria")]
        public string calle { get; set; }

        [Required(ErrorMessage = "El numero es obligatorio")]
        [Display(Name = "Número")]
        public int numero { get; set; }
        [Display(Name = "Colonia")]
        [Required(ErrorMessage = "La colonia es obligatoria")]
        public string colonia { get; set; }

        [Display(Name = "Código Postal")]
        [Required(ErrorMessage = "El código postal es obligatorio")]
        public int codigoPostal { get; set; }

        [Required(ErrorMessage = "El telefono es obligatorio")]
        [Display(Name = "Telefono")]
        public int telefono { get; set; }

        [Required(ErrorMessage = "El RFC es obligatorio")]
        [Display(Name = "RFC")]
        public string rfc { get; set; }

        [Display(Name = "Estatus")]
        public string estatus { get; set; } = "ENVIADO";

        [Display(Name = "Observaciones")]
        public string observaciones { get; set; }

    }
}

Examen/Controllers/HomeController.cs
using Examen.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Examen.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Examen/Controllers/ProspectosController.cs
using Examen.DB;
using Examen.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen.Controllers
{
    public class ProspectosController : Controller
    {

        private readonly ApplicationDbContext _context;

        public ProspectosController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<Prospecto> listaProspectos = _context.Prospecto;
            return View(listaProspectos);
        }

        [HttpPost]
        public IActionResult Captura(Prospecto prospecto)
        {
            if (ModelState.IsValid)
            {
                _context.Prospecto.Add(prospecto);
                _context.SaveChanges();

                return RedirectToAction("Index");

            }

            return View();
        }

        public IActionResult Info(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }

            var prospecto = _context.Prospecto.Find(id);

            if(prospecto == null)
            {
                return NotFound();
            }
            
            return View(prospecto);
        }

        public IActionResult Evaluar(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var prospecto = _context.Prospecto.Find(id);

            if (prospecto == null)
            {
                return NotFound();
            }

            return View(prospecto);
        }

        [HttpPost]
        public IActionResult Evaluar(Prospecto prospecto)
        {
            if (ModelState.IsValid)
            {
                _context.Prospecto.Add(prospecto);
                _context.SaveChanges();

                return RedirectToAction("Index");
                
            }

            return View();
        }
        
        public IActionResult Autorizar(Prospecto prospecto)
        {
            if (ModelState.IsValid)
            {
                prospecto.estatus = "AUTORIZADO";
                prospecto.observaciones = "";
                _context.Prospecto.Add(prospecto);
                _context.SaveChanges();

                return RedirectToAction("Index");

            }

            return View();
        }

        
        public IActionResult Rechazar(Prospecto prospecto)
        {

            if (ModelState.IsValid)
            {
                prospecto.estatus = "RECHAZADO";
                _context.Prospecto.Add(prospecto);
                _context.SaveChanges();

                return RedirectToAction("Index");

            }

            return View();
        }



    }
}

Examen/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Principal";
}

<h3>P&aacute;gina Principal</h3>

Examen/Views/Prospectos/Captura.cshtml
@model  Examen.Models.Prospecto
@{
    ViewData["Title"] = "Nuevo Prospecto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Nueva Captura</h3>

<div class="container">

    <div class="row">
        <form method="post" asp-action="Captura">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row mb-3">
                <div class="col-sm-4">
                    <label class="control-label">Nombre:</label>
                    <input asp-for="nombre" class="form-control">
                    <span asp-validation-for="nombre" class="text-danger"></span>
                </div>

                <div class="col-sm-4">
                    <label class="control-label">Primer Paterno:</label>
                    <input asp-for="apellidoP" class="form-control">
                    <span asp-validation-for="apellidoP" class="text-danger"></span>
                </div>

                <div class="col-sm-4">
                    <label class="control-label">Segundo Paterno:</label>
                    <input asp-for="apellidoM" class="form-control">

                </div>
            </div>
            <div class="row mb-3">
                <div class="col-9">
                    <label class="control-label">Calle:</label>
                    <input asp-for="calle" class="form-control">
                    <span asp-validation-for="calle" class="text-danger"></span>
                </div>
                <div class="col-3">
                    <label class="control-label">N&uacute;mero:</label>
                    <input asp-for="numero" class="form-control">
                    <span asp-validation-for="numero" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-9">
                    <label class="control-label">Colonia:</label>
                    <input asp-for="colonia" class="form-control">
                    <span asp-validation-for="colonia" class="text-danger"></span>
                </div>
                <div class="col-3">
                    <label class="control-label">C&oacute;digo Postal:</label>
                    <input asp-for="codigoPostal" class="form-control">
                    <span asp-validation-for="codigoPostal" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-4">
                    <label class="control-label">Telefono:</label>
                    <input asp-for="telefono" class="form-control">
                    <span asp-validation-for="telefono" class="text-danger"></span>
                </div>
                <div class="col-8">
                    <label class="control-label">RFC:</label>
                    <input asp-for="rfc" class="form-control">
                    <span asp-validation-for="rfc" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group float-right">
                <input type="submit" value="Capturar" class="btn btn-primary" />
                <a class="btn btn-danger" asp-area="" asp-controller="Home" asp-action="Index">Salir</a>
            </div>

        </form>
    </div>
</div>


@section Scripts{ 
    @{ <partial name="_ValidationScriptsPartial"/>}
}

Examen/Views/Prospectos/Evaluar.cshtml
@model Examen.Models.Prospecto
@{
    ViewData["Title"] = "Evaluar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Evaluar</h1>

<div class="container">

    <div class="row">
        <form>
            <input type="hidden" asp-action="Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row mb-3">
                <div class="col-sm-4">
                    <label class="control-label">Nombre:</label>
                    <input asp-for="nombre" class="form-control" disabled>
                </div>

                <div class="col-sm-4">
                    <label class="control-label">Primer Paterno:</label>
                    <input asp-for="apellidoP" class="form-control" disabled>
                </div>

                <div class="col-sm-4">
                    <label class="control-label">Segundo Paterno:</label>
                    <input asp-for="apellidoM" class="form-control" disabled>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-9">
                    <label class="control-label">Calle:</label>
                    <input asp-for="calle" class="form-control" disabled>
                </div>
                <div class="col-3">
                    <label class="control-label">N&uacute;mero:</label>
                    <input asp-for="numero" class="form-control" disabled>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-9">
                    <label class="control-label">Colonia:</label>
                    <input asp-for="colonia" class="form-control" disabled>
                </div>
                <div class="col-3">
                    <label class="control-label">C&oacute;digo Postal:</label>
                    <input asp-for="codigoPostal" class="form-control" disabled>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-4">
                    <label class="control-label">Telefono:</label>
                    <input asp-for="telefono" class="form-control" disabled>
                </div>
                <div class="col-8">
                    <label class="control-label">RFC:</label>
                    <input asp-for="rfc" class="form-control" disabled>
                </div>
            </div>
            <div class="row mb-6">
                <div class="col-12">
                    <textarea asp-for="observaciones"></textarea>
                </div>
            </div>
            <div class="row mb-6 float-right">
                    <a asp-action="Autorizar" class="btn btn-info">Autorizar </a>

                    <a asp-action="Rechazar" class="btn btn-danger">Rechazar </a>
             </div>
        </form>
    </div>
</div>

@section Scripts{
    @{<partial name="_ValidationScriptsPartial" />}
}

Examen/Views/Prospectos/Index.cshtml
@model IEnumerable<Examen.Models.Prospecto>
@{
    ViewData["Title"] = "Listado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h3>Listado de Prospectos</h3>
    </div>

    <div class="row">
        @if(Model.Count() > 0 )
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(m => m.nombre) </td>
                        <td>@Html.DisplayNameFor(m => m.apellidoP) </td>
                        <td>@Html.DisplayNameFor(m => m.apellidoM) </td>
                        <td>@Html.DisplayNameFor(m => m.estatus) </td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in Model)
                    {
                    <tr>
                        <td>@item.nombre </td>
                        <td>@item.apellidoP </td>
                        <td>@item.apellidoM
                        <td>@item.estatus </td>
                        <td>
                            <a asp-controller="Prospectos" asp-action="Info" asp-route-id="@item.Id" class="btn btn-info">Informaci&oacute;n </a>
                            <a asp-controller="Prospectos" asp-action="Evaluar" asp-route-id="@item.Id" class="btn btn-warning">Evaluar </a>
                        </td>

                    </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
          <span>No existen registros</span>
        }
    </div>
</div>

Examen/Views/Prospectos/Info.cshtml
@model Examen.Models.Prospecto

@{
    ViewData["Title"] = "Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Informaci&oacute;n</h1>

<div class="container">

    <div class="row">
        <form>
            <input type="hidden" asp-action="Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row mb-3">
                <div class="col-sm-4">
                    <label class="control-label">Nombre:</label>
                    <input asp-for="nombre" class="form-control" disabled>
                </div>

                <div class="col-sm-4">
                    <label class="control-label">Primer Paterno:</label>
                    <input asp-for="apellidoP" class="form-control" disabled>
                </div>

                <div class="col-sm-4">
                    <label class="control-label">Segundo Paterno:</label>
                    <input asp-for="apellidoM" class="form-control" disabled>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-9">
                    <label class="control-label">Calle:</label>
                    <input asp-for="calle" class="form-control" disabled>
                </div>
                <div class="col-3">
                    <label class="control-label">N&uacute;mero:</label>
                    <input asp-for="numero" class="form-control" disabled>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-9">
                    <label class="control-label">Colonia:</label>
                    <input asp-for="colonia" class="form-control" disabled>
                </div>
                <div class="col-3">
                    <label class="control-label">C&oacute;digo Postal:</label>
                    <input asp-for="codigoPostal" class="form-control" disabled>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-4">
                    <label class="control-label">Telefono:</label>
                    <input asp-for="telefono" class="form-control" disabled>
                </div>
                <div class="col-8">
                    <label class="control-label">RFC:</label>
                    <input asp-for="rfc" class="form-control" disabled>
                </div>
            </div>

            @if (Model.estatus == "RECHAZADO")
            {
                <div class="row mb-3">
                    <textarea asp-for="observaciones"></textarea>
                </div>
            }
</form>
    </div>

</div>

Examen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Examen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Examen</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prospectos" asp-action="Index">Listado</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prospectos" asp-action="Captura">Capturar Prospecto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Examen
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>